version: '3.4'

services:
  nginx:
    container_name: nginx
    image: nginx:1.18
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
